### ISSUE TITLE
Create unit and structure classes

### ISSUE THREAD

**Issue by macmccann** [stonefallio/stonefall#7]

**Comment by macmccann** [comment]
@doyeka @ttsivran I think we should skip the AttackerBean, BaseBean, etc. for now. I think they clutter up the code and don't provide any real benefit as we aren't using any outside sources for our data so we don't need proxies.

**Comment by doyeka** [comment]
Sounds good to me. Since we're just going to be running on strong remote servers we probably won't need them, and we could add them back whenever

**Comment by ttsivran** [comment]
Agreed - they were almost identical objects to the normal ones since the normal ones don't really have much other functionality other than storing info about themselves.
